---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - game.cloud.tencent.com
  resources:
  - rooms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.cloud.tencent.com
  resources:
  - rooms/finalizers
  verbs:
  - update
- apiGroups:
  - game.cloud.tencent.com
  resources:
  - rooms/status
  verbs:
  - get
  - patch
  - update
