# permissions for end users to edit rooms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tke-room-manager
    app.kubernetes.io/managed-by: kustomize
  name: room-editor-role
rules:
- apiGroups:
  - game.cloud.tencent.com
  resources:
  - rooms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.cloud.tencent.com
  resources:
  - rooms/status
  verbs:
  - get
