apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tke-room-server
    app.kubernetes.io/managed-by: kustomize
  name: server
  namespace: system
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: tke-room-server
